version: '3'
services:
  db:
    image: postgres
    restart: always
    ports:
      - '5434:5434'
    environment:
      POSTGRES_PASSWORD: pass123
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
